# numpy Array and operations


In [ ]:
#### Numpy is Numerical python.It is a power full python library used for numerical computating , mathemetical operations , data analysis , and working with multidimensional arrays.

In [5]:
import numpy as np

arr=np.array([10,20,30,40,50])
print(arr)


[10 20 30 40 50]


#### 2D array

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3D arrays

In [7]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### special array creation

In [8]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### onse

In [10]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Indenity matrix

In [11]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### range

In [12]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## Indexing in Numpy

#### Indexing is used to access a specific element from an array.

#### 1D array

In [13]:
arr=np.array([10,20,30,40])
print(arr[0])

10


#### 2d array

In [14]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[0][0])
print(arr[1][2])



1
6


### 3D Array

In [15]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[0,0,0])

1


## slicing in numpy

#### slicing extracts multiple element from an arry

#### 1D Array

In [16]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])
print(arr[:4])
print(arr[3:])

[20 30 40]
[10 20 30 40]
[40 50 60]


#### 2D Array


In [17]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0:2])
print(arr[0:2,1:3])


[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]]


#### 3D array

syntax:[depth,row,column]

depth-> Layer Number
row-> Rows Number
column-> Column Number

In [18]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[0])
print(arr[1])
print(arr[0,0])
print(arr[1,0])
print(arr[0,0,0])
print(arr[0,:,::-1])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[5 6]
1
[[2 1]
 [4 3]]


#### Mathemetical operation

#### numpy perform mathemetical calculations directlyon array.

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.sqrt(a))
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[1 4 9]
